const fs = require('fs');
const path = require('path');

const categoriesData = [
  // 1. FRUITS (30)
  {
    catId: 'fruits',
    catName: 'Fruits',
    prefix: 'f',
    items: [
      { name: 'Organic Apple', sub: 'Citrus Fruits', desc: 'Crisp, sweet, and 100% naturally grown organic apples.', price: 180, unit: 'kg', img: '/images/fruit_apple.jpg', badge: null, cert: '100% Organic', benefits: ['Rich in vitamin C', 'Supports heart health', '100% Chemical Free'] },
      { name: 'Organic Banana', sub: 'Tropical Fruits', desc: 'Naturally ripened organic bananas rich in potassium.', price: 70, unit: 'kg', img: '/images/fruit_banana.jpg', badge: 'Bestseller', cert: '100% Organic', benefits: ['High potassium', 'Natural sweetener', 'Chemical-free ripening'] },
      { name: 'Organic Orange', sub: 'Citrus Fruits', desc: 'Juicy, sun-ripened organic oranges bursting with vitamin C.', price: 120, unit: 'kg', img: '/images/fruit_orange.jpg', badge: null, cert: 'Chemical Free', benefits: ['Immunity support', 'High hydration', 'Zero chemical sprays'] },
      { name: 'Organic Grapes', sub: 'Berries', desc: 'Handpicked sweet seedless organic green and red grapes.', price: 160, unit: 'kg', img: '/images/fruit_grapes.jpg', badge: null, cert: '100% Organic', benefits: ['Antioxidant power', 'Supports healthy skin', 'Natural detoxifier'] },
      { name: 'Organic Pomegranate', sub: 'Tropical Fruits', desc: 'Deep red juicy organic pomegranates directly from farms.', price: 200, unit: 'kg', img: '/images/fruit_pomegranate.jpg', badge: 'Bestseller', cert: '100% Organic', benefits: ['Iron and hemoglobin support', 'Anti-inflammatory', 'Farm fresh'] },
      { name: 'Organic Mango', sub: 'Tropical Fruits', desc: 'Naturally tree-ripened organic Alphonso mangoes.', price: 150, unit: 'kg', img: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=600&auto=format&fit=crop&q=80', badge: null, cert: 'Chemical Free', benefits: ['Rich in vitamin A', 'Naturally tree ripened', 'No carbide treatment'] },
      { name: 'Organic Kiwi', sub: 'Tropical Fruits', desc: 'Tangy-sweet fresh organic kiwis packed with vitamin C.', price: 250, unit: 'kg', img: 'https://images.unsplash.com/photo-1585059895524-72fd596d7827?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Enzyme-rich for digestion', 'Immunity booster', 'Low glycemic index'] },
      { name: 'Organic Mixed Berries', sub: 'Berries', desc: 'Fresh seasonal organic strawberries and blueberries.', price: 300, unit: 'kg', img: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=600&auto=format&fit=crop&q=80', badge: null, cert: 'Chemical Free', benefits: ['Cellular health booster', 'Brain health support', 'Clean & chemical-free'] },
      { name: 'Organic Almonds', sub: 'Dry Fruits', desc: 'Raw organic California almonds packed with protein.', price: 350, unit: '250g', img: 'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['High protein & vitamin E', 'Supports heart health', 'Zero chemical processing'] },
      { name: 'Organic Cashews', sub: 'Dry Fruits', desc: 'Premium organic whole cashew nuts, rich in minerals.', price: 420, unit: '250g', img: 'https://images.unsplash.com/photo-1543362906-acfc16c67564?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Rich in magnesium', 'Creamy texture', 'Handpicked quality'] },
      { name: 'Organic Walnuts', sub: 'Dry Fruits', desc: 'Crisp organic walnut halves rich in Omega-3.', price: 380, unit: '250g', img: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: 'Chemical Free', benefits: ['High in Omega-3', 'Promotes brain function', 'Raw & unbleached'] },
      { name: 'Organic Raisins', sub: 'Dry Fruits', desc: 'Naturally sun-dried sweet organic golden raisins.', price: 180, unit: '250g', img: 'https://images.unsplash.com/photo-1595855759920-86582396756a?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Natural energy booster', 'Iron rich', 'No added sugar'] },
      { name: 'Organic Papaya', sub: 'Tropical Fruits', desc: 'Sweet, vibrant orange organic papayas rich in papain enzyme.', price: 90, unit: 'kg', img: 'https://images.unsplash.com/photo-1517282009859-f000ec3b26fe?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Digestive papain enzyme', 'Skin glowing benefits', 'Pesticide free'] },
      { name: 'Organic Pineapple', sub: 'Tropical Fruits', desc: 'Juicy tropical pineapple rich in bromelain enzyme.', price: 110, unit: 'piece', img: 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=600&auto=format&fit=crop&q=80', badge: null, cert: 'Chemical Free', benefits: ['Anti-inflammatory bromelain', 'Immunity enhancement', 'Naturally sweet'] },
      { name: 'Organic Watermelon', sub: 'Tropical Fruits', desc: 'Refreshing seedless organic watermelon packed with hydration.', price: 60, unit: 'kg', img: 'https://images.unsplash.com/photo-1587049352847-4a222e784d38?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['92% water content', 'Rich in lycopene', 'Cooling & refreshing'] },
      { name: 'Organic Guava', sub: 'Citrus Fruits', desc: 'Crisp green guava with pink flesh, high in vitamin C.', price: 95, unit: 'kg', img: 'https://images.unsplash.com/photo-1536511135882-99079a4053d2?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['4x Vitamin C of oranges', 'Low glycemic index', 'Rich in fibre'] },
      { name: 'Organic Dragon Fruit', sub: 'Tropical Fruits', desc: 'Exotic pink dragonfruit with sweet white dotted flesh.', price: 190, unit: 'piece', img: 'https://images.unsplash.com/photo-1527325678964-549216468488?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Prebiotic fiber', 'Magnesium booster', 'Low calorie detox'] },
      { name: 'Organic Plums', sub: 'Citrus Fruits', desc: 'Juicy sweet and tart organic dark red plums.', price: 210, unit: 'kg', img: 'https://images.unsplash.com/photo-1522184216316-3c25379f963c?w=600&auto=format&fit=crop&q=80', badge: null, cert: 'Chemical Free', benefits: ['Rich in vitamin K & A', 'Bone health support', 'Natural antioxidants'] },
      { name: 'Organic Fresh Figs', sub: 'Tropical Fruits', desc: 'Sweet honey-toned fresh organic figs packed with calcium.', price: 280, unit: 'kg', img: 'https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['High calcium & iron', 'Natural digestive aid', 'Rich in mineral polyphenols'] },
      { name: 'Organic Peach', sub: 'Citrus Fruits', desc: 'Velvety fragrant organic peaches picked at sweet maturity.', price: 230, unit: 'kg', img: 'https://images.unsplash.com/photo-1629828874514-c1e5103f2150?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Skin health vitamins', 'Heart friendly potassium', 'No synthetic wax'] },
      { name: 'Organic Cherries', sub: 'Berries', desc: 'Deep crimson sweet organic cherries packed with melatonin.', price: 450, unit: '500g', img: 'https://images.unsplash.com/photo-1528821128474-27f963b072b7?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['Natural sleep melatonin', 'Anti-inflammatory anthocyanins', 'Joint health support'] },
      { name: 'Organic Pistachios', sub: 'Dry Fruits', desc: 'Lightly roasted organic salted pistachios in shell.', price: 480, unit: '250g', img: 'https://images.unsplash.com/photo-1516054575922-f0b8eeadec1a?w=600&auto=format&fit=crop&q=80', badge: null, cert: 'Chemical Free', benefits: ['Healthy heart fats', 'High lutein & zeaxanthin', 'Sustained energy'] },
      { name: 'Organic Dates', sub: 'Dry Fruits', desc: 'Soft Medjool organic dates, nature’s sweet caramel fruit.', price: 340, unit: '500g', img: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Natural instant energy', 'Rich in potassium', 'Zero refined sugar'] },
      { name: 'Organic Dried Apricots', sub: 'Dry Fruits', desc: 'Sun-dried organic turkish apricots rich in vitamin A.', price: 290, unit: '250g', img: 'https://images.unsplash.com/photo-1595855759920-86582396756a?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Eye health beta-carotene', 'Fiber for digestion', 'Sun-dried natural flavor'] },
      { name: 'Organic Pear', sub: 'Citrus Fruits', desc: 'Crisp green Conference pears with delicate sweet juice.', price: 175, unit: 'kg', img: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Soluble pectin fiber', 'Gentle on stomach', 'Hydrating & crisp'] },
      { name: 'Organic Strawberries', sub: 'Berries', desc: 'Fragrant sweet red organic strawberries free from pesticides.', price: 220, unit: '250g', img: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['Vitamin C superpower', 'Ellagic acid antioxidants', 'Low sugar fruit'] },
      { name: 'Organic Muskmelon', sub: 'Tropical Fruits', desc: 'Sweet aromatic cantaloupe muskmelon packed with hydration.', price: 75, unit: 'kg', img: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=600&auto=format&fit=crop&q=80', badge: null, cert: 'Chemical Free', benefits: ['Summer cooling fruit', 'High vitamin A', 'Electrolyte rich'] },
      { name: 'Organic Custard Apple', sub: 'Tropical Fruits', desc: 'Creamy sweet Sitaphal harvested from rainfed groves.', price: 260, unit: 'kg', img: 'https://images.unsplash.com/photo-1536511135882-99079a4053d2?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Magnesium & B6 vitamins', 'Rich natural sweetness', 'Traditional superfood'] },
      { name: 'Organic Blueberry', sub: 'Berries', desc: 'Handpicked plump wild organic blueberries loaded with antioxidants.', price: 390, unit: '125g', img: 'https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['Top memory booster', 'Anthocyanin rich', 'Supports eye health'] },
      { name: 'Organic Dried Cranberries', sub: 'Dry Fruits', desc: 'Tart-sweet organic dried cranberries for snacking and baking.', price: 320, unit: '250g', img: 'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Urinary tract health', 'Proanthocyanidins', 'No artificial colors'] }
    ]
  },

  // 2. VEGETABLES (30)
  {
    catId: 'vegetables',
    catName: 'Vegetables',
    prefix: 'v',
    items: [
      { name: 'Organic Spinach (Palak)', sub: 'Leafy Vegetables', desc: 'Tender green organic spinach leaves packed with iron and folate.', price: 35, unit: '250g', img: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['High iron & folate', 'Directly farm sourced', 'Zero pesticides'] },
      { name: 'Organic Broccoli', sub: 'Cruciferous Vegetables', desc: 'Vibrant green florets of organic broccoli grown naturally.', price: 60, unit: '250g', img: 'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Sulforaphane detoxifier', 'Crisp & crunchy', 'Sustainably farmed'] },
      { name: 'Organic Carrot', sub: 'Roots & Tubers', desc: 'Farm-fresh sweet red organic carrots loaded with beta-carotene.', price: 40, unit: '500g', img: 'https://images.unsplash.com/photo-1598170845058-12ef4a457511?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['Eye vision support', 'Natural sweet flavor', 'Pesticide free'] },
      { name: 'Organic Tomato', sub: 'Fruits Vegetables', desc: 'Juicy, rich red vine tomatoes grown naturally with compost.', price: 30, unit: '500g', img: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['High Lycopene antioxidant', 'Rich tang flavor', 'Chemical free'] },
      { name: 'Organic Cucumber', sub: 'Gourds & Squash', desc: 'Crisp, cooling organic cucumbers perfect for fresh salad.', price: 25, unit: '500g', img: 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=600&auto=format&fit=crop&q=80', badge: null, cert: 'Chemical Free', benefits: ['95% water hydration', 'Calming digestive detox', 'Naturally grown'] },
      { name: 'Organic Cauliflower', sub: 'Cruciferous Vegetables', desc: 'Pure white pesticide-free organic cauliflower curd.', price: 50, unit: 'piece', img: 'https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['High dietary fiber', 'Low carb nutrition', 'Clean & pest-free'] },
      { name: 'Organic Bell Peppers', sub: 'Fruits Vegetables', desc: 'Vibrant, crunchy organic red and green capsicum.', price: 65, unit: '500g', img: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['High Vitamin C', 'Crisp texture', 'Farm fresh'] },
      { name: 'Organic Potatoes (Aloo)', sub: 'Roots & Tubers', desc: 'Farm-fresh organic potatoes grown in mineral-rich soil.', price: 35, unit: '1 kg', img: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: 'Chemical Free', benefits: ['Rich in complex carbs', 'Organically farmed', 'Zero wax coating'] },
      { name: 'Organic Onions (Pyaz)', sub: 'Roots & Tubers', desc: 'Rich, flavorful organic red onions harvested directly from farms.', price: 45, unit: '1 kg', img: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Rich flavor', 'Natural antioxidants', 'Pesticide free'] },
      { name: 'Organic Green Peas (Matar)', sub: 'Beans & Pulses', desc: 'Tender, naturally sweet organic green peas at peak freshness.', price: 55, unit: '500g', img: 'https://images.unsplash.com/photo-1587735243615-c03f25aaff15?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: 'Chemical Free', benefits: ['High protein and fiber', 'Sweet natural taste', 'Non-GMO'] },
      { name: 'Organic Eggplant (Brinjal)', sub: 'Fruits Vegetables', desc: 'Glossy purple organic brinjal for delicious stews and roasts.', price: 40, unit: '500g', img: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Nasunin brain antioxidant', 'Low calorie food', 'Zero chemical spray'] },
      { name: 'Organic Lady Finger (Bhindi)', sub: 'Beans & Pulses', desc: 'Tender green organic okra rich in dietary fiber and folate.', price: 45, unit: '500g', img: 'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Mucilage for digestion', 'Regulates blood sugar', 'Freshly picked daily'] },
      { name: 'Organic Beetroot', sub: 'Roots & Tubers', desc: 'Deep ruby red organic beetroot loaded with nitrates.', price: 42, unit: '500g', img: 'https://images.unsplash.com/photo-1598170845058-12ef4a457511?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: 'Chemical Free', benefits: ['Stamina & blood circulation', 'Rich in iron & folate', 'Natural blood purifier'] },
      { name: 'Organic Sweet Potato', sub: 'Roots & Tubers', desc: 'Nutrient-dense organic sweet potatoes high in vitamin A.', price: 50, unit: '1 kg', img: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Complex healthy carbs', 'Beta-carotene rich', 'Low GI sweetener'] },
      { name: 'Organic Cabbage', sub: 'Cruciferous Vegetables', desc: 'Crisp green head organic cabbage grown without synthetic sprays.', price: 35, unit: 'piece', img: 'https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Vitamin K & C rich', 'Supports gut microbiota', 'Crisp salad green'] },
      { name: 'Organic Green Chilli', sub: 'Herbs & Greens', desc: 'Spicy, fresh organic green chillies packed with capsaicin.', price: 20, unit: '200g', img: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Capsaicin metabolism boost', 'High Vitamin C', 'Zero pesticide residue'] },
      { name: 'Organic Garlic (Lehsun)', sub: 'Roots & Tubers', desc: 'Pungent organic garlic cloves packed with allicin.', price: 70, unit: '250g', img: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: 'Chemical Free', benefits: ['Allicin immunity defense', 'Heart & BP health', 'Organically cured'] },
      { name: 'Organic Ginger (Adrak)', sub: 'Roots & Tubers', desc: 'Aromatic spicy organic ginger root for tea and cooking.', price: 60, unit: '250g', img: 'https://images.unsplash.com/photo-1598170845058-12ef4a457511?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Gingerol anti-inflammatory', 'Soothes digestion & cold', 'Farm fresh root'] },
      { name: 'Organic Coriander Leaves', sub: 'Herbs & Greens', desc: 'Fragrant fresh green organic coriander leaves.', price: 15, unit: 'bunch', img: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Heavy metal detoxifier', 'Rich herbal aroma', 'Picked same day'] },
      { name: 'Organic Mint Leaves (Pudina)', sub: 'Herbs & Greens', desc: 'Cooling aromatic organic mint leaves for juices and chutney.', price: 15, unit: 'bunch', img: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600&auto=format&fit=crop&q=80', badge: null, cert: 'Chemical Free', benefits: ['Cooling digestive herb', 'Fresh minty flavor', '100% natural'] },
      { name: 'Organic Bottle Gourd (Lauki)', sub: 'Gourds & Squash', desc: 'Tender light green organic lauki, rich in dietary water.', price: 35, unit: 'piece', img: 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Light on digestion', 'Cooling body alkalizer', 'Low calorie food'] },
      { name: 'Organic Bitter Gourd (Karela)', sub: 'Gourds & Squash', desc: 'Fresh green organic karela known for blood sugar support.', price: 40, unit: '500g', img: 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Charantin blood sugar aid', 'Liver detoxifier', 'Zero chemicals'] },
      { name: 'Organic Pumpkin', sub: 'Gourds & Squash', desc: 'Rich golden orange organic pumpkin packed with zinc & fibre.', price: 45, unit: '1 kg', img: 'https://images.unsplash.com/photo-1598170845058-12ef4a457511?w=600&auto=format&fit=crop&q=80', badge: null, cert: 'Chemical Free', benefits: ['Zinc & carotenoid rich', 'Sweet versatile veggie', 'Non-GMO seed'] },
      { name: 'Organic Zucchini', sub: 'Gourds & Squash', desc: 'Tender dark green organic zucchini for pasta and salads.', price: 60, unit: '500g', img: 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Low carb pasta substitute', 'Rich in lutein', 'Pesticide free'] },
      { name: 'Organic Radish (Mooli)', sub: 'Roots & Tubers', desc: 'Crunchy white organic mooli with pungent fresh greens.', price: 30, unit: '500g', img: 'https://images.unsplash.com/photo-1598170845058-12ef4a457511?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Natural digestive enzyme', 'Kidney cleansing', 'Crisp root veggie'] },
      { name: 'Organic Methi (Fenugreek Leaves)', sub: 'Herbs & Greens', desc: 'Fresh aromatic organic methi leaves rich in iron.', price: 20, unit: 'bunch', img: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600&auto=format&fit=crop&q=80', badge: null, cert: 'Chemical Free', benefits: ['Glucose regulation', 'Iron & mineral booster', 'Authentic aroma'] },
      { name: 'Organic French Beans', sub: 'Beans & Pulses', desc: 'Crisp green organic string beans packed with vitamins.', price: 50, unit: '500g', img: 'https://images.unsplash.com/photo-1587735243615-c03f25aaff15?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Silicon for bone health', 'High fiber content', 'Sweet tender pods'] },
      { name: 'Organic Red Capsicum', sub: 'Fruits Vegetables', desc: 'Sweet sun-ripened organic red bell pepper packed with vitamin C.', price: 80, unit: '500g', img: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['Highest Vitamin C pepper', 'Sweet salad crunch', 'Pure organic farm product'] },
      { name: 'Organic Yellow Capsicum', sub: 'Fruits Vegetables', desc: 'Bright yellow organic bell pepper with sweet tropical crunch.', price: 80, unit: '500g', img: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Rich in violaxanthin', 'Vibrant salad color', 'Zero chemical spray'] },
      { name: 'Organic Baby Corn', sub: 'Fruits Vegetables', desc: 'Tender sweet organic baby corn pods for stir-fry and salads.', price: 70, unit: '250g', img: 'https://images.unsplash.com/photo-1587735243615-c03f25aaff15?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Low GI crunchy treat', 'Rich in folate', 'Pesticide free tender pods'] }
    ]
  },

  // 3. COSMETICS (30)
  {
    catId: 'cosmetics',
    catName: 'Cosmetics',
    prefix: 'c',
    items: [
      { name: 'Aloe Vera Face Wash', sub: 'Face Care', desc: 'Gentle organic facial cleanser infused with pure aloe vera.', price: 499, unit: '200 ml', img: '/images/hero_cosmetics.jpg', badge: 'Bestseller', cert: '100% Organic', benefits: ['Deep cleansing without dryness', 'Soothes redness', 'Paraben & sulphate free'] },
      { name: 'Herbal Face Serum', sub: 'Skin Care', desc: 'Radiance boosting botanical serum crafted with plant oils.', price: 799, unit: '30 ml', img: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80', badge: 'Top Rated', cert: '100% Organic', benefits: ['Youthful natural glow', 'Reduces dark spots', '100% plant based'] },
      { name: 'Nourishing Face Cream', sub: 'Face Care', desc: 'Rich moisturizing cream with shea butter and jojoba oil.', price: 599, unit: '50 g', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: 'Chemical Free', benefits: ['24-hour hydration', 'Non-greasy feel', 'Chemical free formula'] },
      { name: 'Neem & Tea Tree Wash', sub: 'Face Care', desc: 'Purifying anti-acne cleanser with organic neem and tea tree.', price: 450, unit: '150 ml', img: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['Controls excess oil', 'Prevents acne breakouts', 'Deep pore cleansing'] },
      { name: 'Kumkumadi Radiance Oil', sub: 'Skin Care', desc: 'Ayurvedic night beauty elixir with saffron and lotus extracts.', price: 999, unit: '30 ml', img: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['Saffron skin brightening', 'Traditional 16-herb formula', 'Evens skin tone'] },
      { name: 'Rose Water Hydrosol', sub: 'Face Care', desc: '100% Pure steam-distilled organic Kannauj rose water.', price: 299, unit: '200 ml', img: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Instant pH balancing toner', 'Tightens open pores', 'Natural floral hydration'] },
      { name: 'Vitamin C Glow Serum', sub: 'Skin Care', desc: '15% Vitamin C serum with hyaluronic acid and ferulic acid.', price: 850, unit: '30 ml', img: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: 'Chemical Free', benefits: ['Fades hyperpigmentation', 'Collagen boosting', 'Antioxidant shield'] },
      { name: 'Shea Butter Body Lotion', sub: 'Body Care', desc: 'Deeply hydrating body cream with cocoa butter & almond oil.', price: 549, unit: '250 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Intense dry skin relief', 'Silky smooth feel', 'No synthetic fragrance'] },
      { name: 'Lavender Body Wash', sub: 'Body Care', desc: 'Relaxing shower gel infused with French lavender essential oil.', price: 475, unit: '300 ml', img: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Calming aromatherapy', 'Sulphate-free cleanser', 'Moisturizing lather'] },
      { name: 'Organic Herbal Soap Bar', sub: 'Body Care', desc: 'Handcrafted cold-processed soap with neem, tulsi and turmeric.', price: 199, unit: '125 g', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Antibacterial protection', 'Natural plant glycerin', 'Zero palm oil'] },
      { name: 'Sunscreen Lotion SPF50', sub: 'Skin Care', desc: 'Mineral broad-spectrum non-nano zinc oxide sunscreen.', price: 699, unit: '100 ml', img: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: 'Chemical Free', benefits: ['UVA/UVB sun protection', 'Reef safe mineral formula', 'No white cast'] },
      { name: 'Organic Lip Balm', sub: 'Lip Care', desc: 'Nourishing beeswax lip balm with coconut oil and strawberry.', price: 175, unit: '10 g', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Heals chapped lips', 'Long lasting moisture', 'Edible natural ingredients'] },
      { name: 'Ubtan Face Pack', sub: 'Face Care', desc: 'Traditional herbal bridal scrub with turmeric and gram flour.', price: 399, unit: '100 g', img: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Removes suntan', 'Exfoliates dead skin', 'Gives instant glow'] },
      { name: 'Charcoal Detox Scrub', sub: 'Face Care', desc: 'Activated bamboo charcoal face scrub with walnut shell granules.', price: 425, unit: '100 g', img: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80', badge: null, cert: 'Chemical Free', benefits: ['Pulls out blackheads', 'Unclogs facial pores', 'Detoxifies skin'] },
      { name: 'Under Eye Cream', sub: 'Skin Care', desc: 'Coffee and green tea extract cream for dark circles and puffiness.', price: 525, unit: '25 g', img: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['Reduces dark circles', 'Smoothes fine lines', 'De-puffs tired eyes'] },
      { name: 'Papaya Glow Face Mask', sub: 'Face Care', desc: 'Enzyme clay mask with papaya extract for glowing smooth skin.', price: 449, unit: '100 g', img: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Gently exfoliates skin', 'Restores natural radiance', 'Reduces blemishes'] },
      { name: 'Tea Tree Spot Gel', sub: 'Face Care', desc: 'Targeted acne treatment gel with Australian tea tree oil.', price: 325, unit: '15 ml', img: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80', badge: null, cert: 'Chemical Free', benefits: ['Shrinks pimples overnight', 'Calms inflammation', 'Clear skin gel'] },
      { name: 'Saffron Night Cream', sub: 'Face Care', desc: 'Overnight cell repair cream with Kashmiri saffron and niacinamide.', price: 899, unit: '50 g', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['Overnight skin renewal', 'Improves skin elasticity', 'Luminous complexion'] },
      { name: 'Organic Foot Cream', sub: 'Personal Care', desc: 'Peppermint and tea tree cracked heel repair cream.', price: 375, unit: '100 g', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Heals deep heel cracks', 'Deodorizing peppermint', 'Softens rough skin'] },
      { name: 'Organic Hand Cream', sub: 'Personal Care', desc: 'Almond oil and shea butter non-greasy hand moisturizer.', price: 299, unit: '75 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Protects dry hands', 'Fast absorbing formula', 'Cuticle care'] },
      { name: 'Rose Clay Face Mask', sub: 'Face Care', desc: 'French pink clay mask with rosehip oil for sensitive skin.', price: 475, unit: '100 g', img: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Removes impurities', 'Ultra gentle on skin', 'Nourishes dry patches'] },
      { name: 'Bakuchiol Anti-Aging Oil', sub: 'Skin Care', desc: 'Natural plant retinol alternative oil with squalane.', price: 950, unit: '30 ml', img: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80', badge: 'Top Rated', cert: '100% Organic', benefits: ['Smoothes fine wrinkles', 'No retinol irritation', 'Plumps skin texture'] },
      { name: 'Organic Body Butter', sub: 'Body Care', desc: 'Rich whipped mango butter & argan oil body balm.', price: 650, unit: '200 g', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Deep winter hydration', 'Whipped creamy texture', 'Delicious natural scent'] },
      { name: 'Cucumber Cooling Eye Gel', sub: 'Skin Care', desc: 'Refreshing cucumber & hyaluronic acid eye gel pad.', price: 349, unit: '30 g', img: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80', badge: null, cert: 'Chemical Free', benefits: ['Instant eye cooling', 'Soothes computer strain', 'Reduces eye bags'] },
      { name: 'Makeup Remover Oil', sub: 'Personal Care', desc: 'Cold-pressed jojoba & castor cleansing oil for waterproof makeup.', price: 425, unit: '150 ml', img: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Dissolves heavy makeup', 'No harsh chemicals', 'Leaves skin soft'] },
      { name: 'Jasmine Body Oil', sub: 'Body Care', desc: 'Aromatic massage body oil with wild jasmine & sesame oil.', price: 575, unit: '200 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Lush jasmine fragrance', 'Silky body massage oil', 'Nourishes dry skin'] },
      { name: 'Green Tea Cleansing Foam', sub: 'Face Care', desc: 'Antioxidant rich foaming face wash with matcha extract.', price: 475, unit: '150 ml', img: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Gentle airy foam', 'Controls T-zone shine', 'Rich in polyphenol'] },
      { name: 'Organic Lip Scrub', sub: 'Lip Care', desc: 'Exfoliating cane sugar and coconut oil lip polish.', price: 220, unit: '15 g', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Buffs away dry skin', 'Makes lips soft', 'Sweet vanilla taste'] },
      { name: 'De-Tan Face Gel', sub: 'Face Care', desc: 'Cooling cucumber and turmeric gel for sun-tanned skin.', price: 349, unit: '100 g', img: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80', badge: null, cert: 'Chemical Free', benefits: ['Soothes sunburn', 'Lightens sun tan', 'Cooling gel feel'] },
      { name: 'Hyaluronic Acid Face Mist', sub: 'Face Care', desc: 'Hydrating facial spray with aloe, rose & hyaluronic acid.', price: 399, unit: '100 ml', img: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['Mid-day skin refresher', 'Plumps skin hydration', 'Sets mineral makeup'] }
    ]
  },

  // 4. HAIR OILS (30)
  {
    catId: 'hair-oils',
    catName: 'Hair Oils',
    prefix: 'h',
    items: [
      { name: 'Cold Pressed Coconut Oil', sub: 'Coconut Oil', desc: '100% Pure unrefined virgin coconut oil for scalp nourishment.', price: 350, unit: '500 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['Deep root conditioning', 'Prevents protein loss', '100% pure & edible'] },
      { name: 'Bhringraj Ayurvedic Oil', sub: 'Bhringraj Oil', desc: 'Traditional herb-infused oil to reduce hair fall and promote growth.', price: 499, unit: '200 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['Controls hair fall', 'Stimulates new roots', 'Traditional taila formula'] },
      { name: 'Amla & Brahmi Hair Oil', sub: 'Amla Oil', desc: 'Vitamin C rich amla oil to strengthen hair roots and darken hair.', price: 399, unit: '200 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Prevents premature graying', 'Thickens fine hair', 'Cools head & mind'] },
      { name: 'Red Onion Hair Seed Oil', sub: 'Onion Oil', desc: 'Black seed & red onion oil formula for rapid hair regrowth.', price: 549, unit: '200 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: 'Chemical Free', benefits: ['Sulphur rich root boost', 'Reduces breakage', 'Non-sticky formula'] },
      { name: 'Pure Jamaican Castor Oil', sub: 'Castor Oil', desc: 'Thick unrefined castor oil for hair volume and eyebrow growth.', price: 425, unit: '200 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Ricinoleic acid formula', 'Promotes thick regrowth', 'Moisturizes dry scalp'] },
      { name: 'Rosemary Scalp Serum Oil', sub: 'Rosemary Oil', desc: 'Pure rosemary essential oil infused scalp growth elixir.', price: 599, unit: '100 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: 'Top Rated', cert: '100% Organic', benefits: ['Clinically proven growth', 'Improves blood flow', 'Pleasant herbal scent'] },
      { name: 'Sweet Almond Hair Oil', sub: 'Herbal Hair Oil', desc: 'Cold pressed almond oil rich in Vitamin E for shiny hair.', price: 450, unit: '200 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Light non-greasy oil', 'Softens rough hair ends', 'High Vitamin E'] },
      { name: 'Moroccan Argan Hair Oil', sub: 'Herbal Hair Oil', desc: 'Liquid gold argan oil to tame frizz and add mirror shine.', price: 799, unit: '100 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: 'Chemical Free', benefits: ['Anti-frizz smoothing', 'Heat styling protectant', 'Silky hair finish'] },
      { name: 'Hibiscus Root Therapy Oil', sub: 'Herbal Hair Oil', desc: 'Red hibiscus flower oil for deep scalp conditioning.', price: 475, unit: '200 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Prevents split ends', 'Conditions dry scalp', 'Natural hair shine'] },
      { name: 'Neem Anti-Dandruff Oil', sub: 'Herbal Hair Oil', desc: 'Purifying neem & tea tree scalp oil to eliminate flakes.', price: 375, unit: '200 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Cures itchy scalp', 'Removes stubborn flakes', 'Antifungal neem formula'] },
      { name: 'Brahmi & Jatamansi Oil', sub: 'Herbal Hair Oil', desc: 'Cooling herbal oil to promote deep sleep and calm mind.', price: 425, unit: '200 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Relieves stress & headache', 'Cooling head massage', 'Strengthens hair roots'] },
      { name: 'Sesame Seed (Til) Oil', sub: 'Herbal Hair Oil', desc: 'Pure black sesame seed oil for traditional Ayurvedic champi.', price: 320, unit: '500 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Warming head massage', 'Deep scalp penetration', 'Rich in omega fats'] },
      { name: 'Kalonji (Black Seed) Oil', sub: 'Herbal Hair Oil', desc: 'Pure cold-pressed black seed oil for thinning hair.', price: 520, unit: '150 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: 'Chemical Free', benefits: ['Restores thinning hair', 'Thymoquinone power', 'Nourishes scalp'] },
      { name: 'Curry Leaf Hair Growth Oil', sub: 'Herbal Hair Oil', desc: 'Fresh curry leaf and coconut infused oil for dark thick hair.', price: 410, unit: '200 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Prevents premature greying', 'Beta-carotene rich', 'Roots strengthening'] },
      { name: 'Fenugreek (Methi) Oil', sub: 'Herbal Hair Oil', desc: 'Methi seed infusion for silky soft hair and dandruff control.', price: 380, unit: '200 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Natural hair protein', 'Adds bounce & shine', 'Reduces hair thinning'] },
      { name: 'Jojoba Golden Scalp Oil', sub: 'Herbal Hair Oil', desc: 'Pure unrefined jojoba oil that mimics natural scalp sebum.', price: 650, unit: '100 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Balances scalp oiliness', 'Non-clogging formula', 'Deep follicle hydration'] },
      { name: 'Walnut Hair Nourishing Oil', sub: 'Herbal Hair Oil', desc: 'Rich walnut oil loaded with biotin and copper minerals.', price: 490, unit: '200 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: 'Chemical Free', benefits: ['Biotin root booster', 'Enhances hair color', 'Silky hair texture'] },
      { name: 'Mustard (Sarson) Hair Oil', sub: 'Herbal Hair Oil', desc: 'Traditional cold pressed Kachi Ghani mustard oil.', price: 250, unit: '500 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Stimulates blood circulation', 'Warming scalp care', '100% pure & unrefined'] },
      { name: 'Shikakai & Reetha Hair Oil', sub: 'Herbal Hair Oil', desc: 'Natural cleanser oil for healthy roots and shiny strands.', price: 360, unit: '200 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Natural saponin shine', 'Gentle scalp care', 'Prevents hair dryness'] },
      { name: 'Aloe Vera Hair Serum Oil', sub: 'Herbal Hair Oil', desc: 'Lightweight leave-in serum oil with aloe vera & argan.', price: 440, unit: '100 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Anti-frizz leave-in', 'Thermal protection', 'Non-sticky gloss'] },
      { name: 'Mahabhringraj Hair Oil', sub: 'Bhringraj Oil', desc: 'Potent concentrated Mahabhringraj oil brewed with milk.', price: 580, unit: '200 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['Intensive hair fall stop', 'Classical Siddha recipe', 'Thick dense regrowth'] },
      { name: 'Tea Tree Scalp Oil', sub: 'Herbal Hair Oil', desc: 'Tea tree & rosemary oil blend for itchy flake-prone scalp.', price: 410, unit: '150 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: 'Chemical Free', benefits: ['Antiseptic scalp relief', 'Soothes inflammation', 'Fresh herbal aroma'] },
      { name: 'Avocado Extra Virgin Oil', sub: 'Herbal Hair Oil', desc: 'Rich green avocado oil for extremely dry brittle hair.', price: 620, unit: '100 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Monounsaturated fat hydration', 'Penetrates hair shaft', 'Repairs damaged ends'] },
      { name: 'Grapeseed Light Hair Oil', sub: 'Herbal Hair Oil', desc: 'Feather-light non-greasy oil for fine thin hair.', price: 470, unit: '150 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Zero weight on fine hair', 'Linoleic acid rich', 'Natural heat tamer'] },
      { name: 'Henna & Indigo Hair Oil', sub: 'Herbal Hair Oil', desc: 'Botanical oil blend that maintains rich dark hair tone.', price: 395, unit: '200 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Protects hair dye color', 'Natural sheen booster', 'Conditions dark hair'] },
      { name: 'Macadamia Nut Hair Oil', sub: 'Herbal Hair Oil', desc: 'Ultra-nourishing macadamia oil for coarse curly hair.', price: 740, unit: '100 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Curl pattern definition', 'Squalan-like hydration', 'Reduces tangle'] },
      { name: 'Peppermint Scalp Tonic Oil', sub: 'Herbal Hair Oil', desc: 'Tingling peppermint & camphor oil to wake up tired hair roots.', price: 430, unit: '150 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: 'Chemical Free', benefits: ['Stimulating scalp tingle', 'Cleanses follicle buildup', 'Energizing aroma'] },
      { name: 'Pumpkin Seed Hair Oil', sub: 'Herbal Hair Oil', desc: 'Cold pressed pumpkin seed oil naturally rich in DHT blockers.', price: 560, unit: '150 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['Natural DHT blocker', 'Reduces male pattern loss', 'High in zinc & omega-6'] },
      { name: 'Wheatgerm Vitamin E Oil', sub: 'Herbal Hair Oil', desc: 'Dense antioxidant wheatgerm oil for scalp repair.', price: 490, unit: '100 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Highest natural Vitamin E', 'Repairs chemical damage', 'Softens stiff hair'] },
      { name: '18-Herb Champi Hair Oil', sub: 'Herbal Hair Oil', desc: 'Master blend of 18 Ayurvedic herbs in sesame & coconut base.', price: 599, unit: '250 ml', img: 'https://images.unsplash.com/photo-1608248597261-833258657640?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['Complete hair & scalp care', 'Handmade wooden churned', 'Zero mineral oil'] }
    ]
  },

  // 5. ORG CHEMICALS (30)
  {
    catId: 'org-chemicals',
    catName: 'Org Chemicals',
    prefix: 'oc',
    items: [
      { name: 'Neem Oil Bio Pesticide', sub: 'Bio Pesticides', desc: '100% Pure cold pressed 10000 PPM Azadirachtin neem oil for organic pest control.', price: 450, unit: '500 ml', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['Controls 200+ pest species', 'Safe for honeybees', '100% biodegradable'] },
      { name: 'Trichoderma Bio Fungicide', sub: 'Bio Fungicides', desc: 'Eco-certified Trichoderma Viride bio fungicide powder for root rot control.', price: 299, unit: '1 kg', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Prevents wilt & root rot', 'Protects seedling roots', 'Soil beneficial fungus'] },
      { name: 'Pseudomonas Bio Liquid', sub: 'Bio Fungicides', desc: 'Pseudomonas Fluorescens liquid culture for blight & mildew control.', price: 349, unit: '1 L', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: 'Chemical Free', benefits: ['Bacterial disease shield', 'Promotes root elongation', 'Eco friendly spray'] },
      { name: 'Seaweed Extract Liquid', sub: 'Plant Growth Promoters', desc: 'Concentrated Ascophyllum Nodosum liquid seaweed growth stimulant.', price: 499, unit: '500 ml', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['Boosts flower & fruit set', '60+ natural micro trace elements', 'Increases drought resistance'] },
      { name: 'Humic Acid Liquid 12%', sub: 'Soil Conditioners', desc: 'Organic potassium humate liquid for soil structure improvement.', price: 399, unit: '1 L', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Enhances nutrient uptake', 'Loosens clay soil', 'Stimulates soil microbes'] },
      { name: 'Fulvic Acid Powder 90%', sub: 'Plant Growth Promoters', desc: 'Water soluble bio-active fulvic acid for foliar nutrient absorption.', price: 549, unit: '250 g', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Chelates micro minerals', 'Fast foliar penetration', 'Boosts photosynthesis'] },
      { name: 'Beauveria Bio Insecticide', sub: 'Bio Insecticides', desc: 'Beauveria Bassiana entomopathogenic fungus against caterpillars & borer.', price: 380, unit: '1 kg', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: 'Chemical Free', benefits: ['Natural whitefly & borer kill', 'Zero chemical residue', 'Safe for mammals'] },
      { name: 'Metarhizium Bio Control', sub: 'Bio Insecticides', desc: 'Metarhizium Anisopliae liquid bio insect control for termites and grubs.', price: 420, unit: '1 L', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Kills soil white grubs', 'Termite colony control', 'Eco friendly soil spray'] },
      { name: 'Azospirillum Biofertilizer', sub: 'Soil Conditioners', desc: 'Nitrogen fixing Azospirillum bio-inoculant for crops and grains.', price: 250, unit: '1 kg', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Atmospheric N2 fixation', 'Reduces urea dependence', 'Produces root hormones'] },
      { name: 'Rhizobium Culture Powder', sub: 'Seed Treatment', desc: 'Legume seed inoculant for high nitrogen fixing in pulses.', price: 220, unit: '500 g', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Forms root nodules', 'Increases pulse yield', 'Natural bio N source'] },
      { name: 'Mycorrhiza VAM Granules', sub: 'Soil Conditioners', desc: 'Vesicular Arbuscular Mycorrhizae bio-fertilizer for root network.', price: 475, unit: '1 kg', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['100x Root surface extension', 'Phosphorus solubilizer', 'Improves water absorption'] },
      { name: 'Vermi Wash Liquid Extract', sub: 'Leaf Nutrients', desc: 'Liquid nutrient tonic collected during organic earthworm composting.', price: 280, unit: '1 L', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Rich in auxins & cytokinins', 'Prevents leaf yellowing', 'Natural foliar spray'] },
      { name: 'Bio NPK Consortium', sub: 'Soil Conditioners', desc: 'Liquid microbial consortium containing N-fixer, P & K solubilizers.', price: 499, unit: '1 L', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['All-in-one NPK micro-flora', 'Unlocks bound soil minerals', 'Improves crop quality'] },
      { name: 'Panchagavya Organic Spray', sub: 'Plant Growth Promoters', desc: 'Fermented traditional 5-cow product bio-booster for green growth.', price: 350, unit: '1 L', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Traditional Vedic bio-booster', 'Imparts pest immunity', 'Accelerates vegetative growth'] },
      { name: 'Karanja Oil Pesticide', sub: 'Bio Pesticides', desc: 'Cold pressed Pongamia Pinnata oil for sucking insect pest control.', price: 390, unit: '500 ml', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: 'Chemical Free', benefits: ['Kills mites & mealybugs', 'Synergistic with neem oil', 'Non-toxic bio spray'] },
      { name: 'Jeevamrutha Bio Starter', sub: 'Compost Activators', desc: 'Concentrated dry microbial powder to prepare fresh Jeevamrut at home.', price: 299, unit: '500 g', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Multiplies soil earthworms', 'Zero cost natural farming', 'Revives dead soil'] },
      { name: 'Bio Zinc Solubilizer', sub: 'Leaf Nutrients', desc: 'ZSB bacteria liquid culture to correct zinc deficiency in plants.', price: 310, unit: '1 L', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Cures leaf bronzing', 'Unlocks soil insoluble Zn', 'Boosts enzyme formation'] },
      { name: 'Bio Potash Solubilizer', sub: 'Leaf Nutrients', desc: 'Frateuria Aurantia bacteria for potassic nutrient mobilization.', price: 340, unit: '1 L', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Increases fruit sweetness', 'Improves grain weight', 'Natural potash bio-source'] },
      { name: 'Chitosan Plant Elixir', sub: 'Plant Growth Promoters', desc: 'Crab shell bio-polymeric systemic acquired resistance stimulant.', price: 650, unit: '250 ml', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Triggers plant immunity', 'Protects against fungal attack', 'Thickens leaf cell walls'] },
      { name: 'Compost Bio Activator', sub: 'Compost Activators', desc: 'Cellulolytic microbial culture for 3x faster waste composting.', price: 275, unit: '1 kg', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Odor-free waste decay', 'Breaks down dry leaves', 'Ready compost in 30 days'] },
      { name: 'Bacillus Thuringiensis (Bt)', sub: 'Bio Insecticides', desc: 'Bt Kurstaki bio-insecticide powder for leaf eating caterpillar control.', price: 399, unit: '500 g', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: 'Chemical Free', benefits: ['Targeted caterpillar kill', 'Harmless to beneficial bugs', 'Organic farming approved'] },
      { name: 'Silica Bio Booster', sub: 'Plant Growth Promoters', desc: 'Soluble bio-silicon liquid to strengthen plant stems against lodging.', price: 425, unit: '500 ml', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Erect sturdy plant stems', 'Reduces heat & cold stress', 'Discourages biting insects'] },
      { name: 'Verticillium Lecanii', sub: 'Bio Insecticides', desc: 'Entomopathogenic fungus liquid against mealybugs, aphids & thrips.', price: 365, unit: '1 L', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['White halo disease fungus', 'Eliminates sticky honeydew', 'Safe bio spray'] },
      { name: 'Bio Sulfur Fungicide', sub: 'Bio Fungicides', desc: 'Micro-granule elemental bio sulfur for powdery mildew and mite control.', price: 240, unit: '1 kg', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: 'Chemical Free', benefits: ['Dual fungicide & miticide', 'Provides essential sulfur', 'Eco garden spray'] },
      { name: 'Gibberellic Acid (GA3) Bio', sub: 'Plant Growth Promoters', desc: 'Natural fungal fermentation GA3 growth hormone for fruit sizing.', price: 480, unit: '100 ml', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Enlarges berry & fruit size', 'Breaks seed dormancy', 'Stimulates stem elongation'] },
      { name: 'Ampelomyces Bio Powder', sub: 'Bio Fungicides', desc: 'Hyper-parasitic bio control fungus against powdery mildew.', price: 390, unit: '500 g', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Parasitizes white mildew', 'Preventative leaf spray', 'Zero harvest waiting time'] },
      { name: 'Bio Boron Solubilizer', sub: 'Leaf Nutrients', desc: 'Bacterial culture mobilizing boron for fruit cracking prevention.', price: 330, unit: '1 L', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Prevents fruit splitting', 'Improves pollen germination', 'Ensures uniform fruit set'] },
      { name: 'Paecilomyces Bio Nematicide', sub: 'Bio Insecticides', desc: 'Bio-control fungus targeting destructive soil root-knot nematodes.', price: 440, unit: '1 kg', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Destroys nematode eggs', 'Clears root galls & knots', 'Restores healthy root feeder'] },
      { name: 'Brassinolide Growth Bio', sub: 'Plant Growth Promoters', desc: 'Plant steroid hormone for extreme temperature stress recovery.', price: 590, unit: '100 ml', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: 'Top Rated', cert: '100% Organic', benefits: ['Helps plants survive drought', 'Restores stunted growth', 'Boosts seed germination'] },
      { name: 'Wetting Agent (Bio Spreader)', sub: 'Plant Growth Promoters', desc: 'Non-ionic organic silicon spreader sticker for uniform spray coverage.', price: 299, unit: '250 ml', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: 'Chemical Free', benefits: ['10x Spray spreading', 'Prevents spray runoff', 'Rain-fastness booster'] }
    ]
  },

  // 6. FERTILIZERS (30)
  {
    catId: 'fertilizers',
    catName: 'Fertilizers',
    prefix: 'fer',
    items: [
      { name: 'Premium Vermicompost 5kg', sub: 'Vermicompost', desc: 'Black gold 100% pure organic earthworm castings packed with humic microbes.', price: 299, unit: '5 kg', img: '/images/hero_fertilizer.jpg', badge: 'Bestseller', cert: '100% Organic', benefits: ['Rich in NPK and humic acid', 'Improves soil aeration', 'Zero chemical additives'] },
      { name: 'Organic Cow Dung Manure', sub: 'Organic Manure', desc: 'Fully composted odorless aged cow manure for rich garden beds.', price: 199, unit: '5 kg', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Natural slow release NPK', 'Restores soil structure', 'Weed-seed free compost'] },
      { name: 'Steamed Bone Meal Powder', sub: 'Bone Meal', desc: 'Natural organic source of phosphorus & calcium for healthy plant roots.', price: 249, unit: '1 kg', img: '/images/hero_fertilizer.jpg', badge: null, cert: '100% Organic', benefits: ['Phosphorus & calcium rich', 'Promotes strong roots', 'Boosts flower blossoms'] },
      { name: 'Pure Neem Cake Powder', sub: 'Neem Cake', desc: 'Cold pressed organic neem cake manure to enrich soil & repel pests.', price: 175, unit: '1 kg', img: '/images/hero_fertilizer.jpg', badge: 'Bestseller', cert: '100% Organic', benefits: ['Natural soil nematicide', 'Slow release nitrogen', 'Protects roots from grubs'] },
      { name: 'Mustard Oil Cake Powder', sub: 'Organic Manure', desc: 'Traditional Sarson Khali organic plant food for leafy green growth.', price: 150, unit: '1 kg', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['High protein & nitrogen', 'Boosts vegetable size', 'Great for potting mix'] },
      { name: 'Bio NPK Organic Fertilizer', sub: 'Bio Fertilizers', desc: 'Enriched bio-organic granules containing beneficial N-P-K bacteria.', price: 349, unit: '2 kg', img: '/images/hero_fertilizer.jpg', badge: 'Bestseller', cert: '100% Organic', benefits: ['Balanced plant nutrition', 'Improves soil biodiversity', 'Sustained plant vigor'] },
      { name: 'Organic Potting Soil Mix', sub: 'Potting Soil', desc: 'Ready-to-use enriched soil with cocopeat, vermicompost & neem cake.', price: 299, unit: '5 kg', img: '/images/hero_fertilizer.jpg', badge: null, cert: '100% Organic', benefits: ['Lightweight & breathable', 'Retains ideal moisture', 'Ready for seeds & plants'] },
      { name: 'Seaweed Fertilizer Granules', sub: 'Bio Fertilizers', desc: 'Cold-water kelp extract bio granules for root and fruit enlargement.', price: 399, unit: '1 kg', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Rich in natural cytokinins', 'Reduces transplant shock', 'Improves crop yield'] },
      { name: 'Epsom Salt (Magnesium Sulfate)', sub: 'Bio Fertilizers', desc: '100% Pure garden grade Epsom salt for green lush leaves & sweet fruits.', price: 180, unit: '1 kg', img: '/images/hero_fertilizer.jpg', badge: null, cert: 'Chemical Free', benefits: ['Cures leaf yellowing', 'Magnesium & sulfur source', 'Enhances green chlorophyll'] },
      { name: 'Rock Phosphate Powder', sub: 'Bio Fertilizers', desc: 'Natural soft rock phosphate for organic phosphorus soil building.', price: 220, unit: '2 kg', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Long term phosphorus source', 'Builds strong plant stems', 'Ideal for fruit trees'] },
      { name: 'Bio Potash Granules', sub: 'Bio Fertilizers', desc: 'Organic potassium fertilizer derived from molasses & bio-minerals.', price: 320, unit: '2 kg', img: '/images/hero_fertilizer.jpg', badge: null, cert: '100% Organic', benefits: ['Increases fruit weight & color', 'Disease resistance booster', 'Eco friendly potash'] },
      { name: 'Perlite & Vermiculite Mix', sub: 'Potting Soil', desc: 'Premium soil conditioner for succulent, bonsai and seed germination.', price: 260, unit: '2 L', img: '/images/hero_fertilizer.jpg', badge: null, cert: '100% Organic', benefits: ['Superb soil aeration', 'Prevents soil compaction', 'Ideal root drainage'] },
      { name: 'Cocopeat Block 5kg', sub: 'Potting Soil', desc: 'Washed low-EC coconut coir peat block expanding to 75 liters.', price: 350, unit: '5 kg', img: '/images/hero_fertilizer.jpg', badge: 'Bestseller', cert: '100% Organic', benefits: ['Holds 5x water weight', 'Low salt EC tested', '100% peat free media'] },
      { name: 'Organic Rose Food Mix', sub: 'Organic Manure', desc: 'Specialized organic fertilizer for abundant rose blooms and vibrant colors.', price: 275, unit: '1 kg', img: '/images/hero_fertilizer.jpg', badge: 'Bestseller', cert: '100% Organic', benefits: ['Maximum flower buds', 'Enhances flower fragrance', 'Protects from die-back'] },
      { name: 'Vegetable Special Fertilizer', sub: 'Organic Manure', desc: 'Balanced bio-organic plant food tailored for home vegetable gardens.', price: 310, unit: '1 kg', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Juicy larger vegetables', 'Continuous harvesting', 'Safe for edible food'] },
      { name: 'Fruit Plant Booster Manure', sub: 'Organic Manure', desc: 'Micro-nutrient enriched manure for mango, lemon, guava & citrus trees.', price: 380, unit: '2 kg', img: '/images/hero_fertilizer.jpg', badge: null, cert: '100% Organic', benefits: ['Prevents fruit drop', 'Increases fruit sweetness', 'Deep root feeding'] },
      { name: 'Bio Zinc Granules', sub: 'Bio Fertilizers', desc: 'Soil application zinc bio-granules for healthy leaf development.', price: 240, unit: '1 kg', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Cures little-leaf disease', 'Boosts auxin synthesis', 'Improves plant growth'] },
      { name: 'Humic Acid Granules 70%', sub: 'Bio Fertilizers', desc: 'Concentrated potassium humate soil granules for long term fertility.', price: 450, unit: '1 kg', img: '/images/hero_fertilizer.jpg', badge: 'Bestseller', cert: '100% Organic', benefits: ['Multiplies soil flora', 'Prevents nutrient leaching', 'Darkens topsoil'] },
      { name: 'Hydroton Clay Pebbles', sub: 'Potting Soil', desc: 'Expanded clay pebbles for hydroponics, drainage & terrarium decoration.', price: 320, unit: '5 L', img: '/images/hero_fertilizer.jpg', badge: null, cert: '100% Organic', benefits: ['pH neutral drainage layer', 'Re-usable clay pebbles', 'Ideal hydroponics media'] },
      { name: 'Organic Lawn Turf Feed', sub: 'Organic Manure', desc: 'Slow release nitrogen organic lawn food for dense green grass carpet.', price: 420, unit: '3 kg', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Lush deep green lawn', 'Prevents weed invasion', 'Pet & child safe lawn food'] },
      { name: 'Castor Cake Powder', sub: 'Organic Manure', desc: 'Organic castor meal rich in nitrogen, phosphorus and natural alkaloids.', price: 165, unit: '1 kg', img: '/images/hero_fertilizer.jpg', badge: null, cert: '100% Organic', benefits: ['Kills soil nematodes', 'Slow release plant food', 'Great for fruit crops'] },
      { name: 'Indoor Plant Food Sticks', sub: 'Bio Fertilizers', desc: 'Mess-free slow release organic fertilizer spikes for indoor pots.', price: 199, unit: '30 spikes', img: '/images/hero_fertilizer.jpg', badge: null, cert: 'Chemical Free', benefits: ['Feed for 60 days', 'Odorless spike design', 'No mess or measuring'] },
      { name: 'Organic Citrus Plant Food', sub: 'Organic Manure', desc: 'Acidic bio fertilizer enriched with iron & magnesium for citrus trees.', price: 295, unit: '1 kg', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Juicy sweet lemons', 'Prevents iron chlorosis', 'Rich in natural sulfur'] },
      { name: 'Pith & Coir Compost', sub: 'Potting Soil', desc: 'Aged coir pith compost enriched with beneficial bio-culture.', price: 220, unit: '5 kg', img: '/images/hero_fertilizer.jpg', badge: null, cert: '100% Organic', benefits: ['Sustainable soil amendment', 'Excellent root hydration', 'Eco friendly garden bed'] },
      { name: 'Organic Flowering Booster', sub: 'Bio Fertilizers', desc: 'High phosphorus & potash organic booster for ornamental garden flowers.', price: 340, unit: '1 kg', img: '/images/hero_fertilizer.jpg', badge: 'Bestseller', cert: '100% Organic', benefits: ['Doubles flower production', 'Brightens petal colors', 'Prevents bud drop'] },
      { name: 'Fish Amino Acid Liquid', sub: 'Bio Fertilizers', desc: 'Fermented fish & jaggery natural amino acid plant growth liquid.', price: 399, unit: '500 ml', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['17 essential amino acids', 'Instant green foliar surge', 'Vedic Korean farming tonic'] },
      { name: 'Wood Ash Potassium Soil Aid', sub: 'Organic Manure', desc: 'Sifted natural hardwood ash rich in potassium, calcium & trace minerals.', price: 140, unit: '1 kg', img: '/images/hero_fertilizer.jpg', badge: null, cert: '100% Organic', benefits: ['Neutralizes acidic soil', 'Natural slug repellent', 'Rich organic potash source'] },
      { name: 'Mycorrhiza Root Granules', sub: 'Bio Fertilizers', desc: 'Granular VAM root helper for all flowering and vegetable crops.', price: 360, unit: '1 kg', img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Expands root absorb zone', 'Drought resilience', 'Enhanced P uptake'] },
      { name: 'Azolla Bio Feed Granules', sub: 'Bio Fertilizers', desc: 'Dried organic Azolla fern granules high in protein & nitrogen.', price: 250, unit: '1 kg', img: '/images/hero_fertilizer.jpg', badge: null, cert: '100% Organic', benefits: ['Bio-nitrogen green manure', 'Improves soil humus', '100% natural green fern'] },
      { name: 'Organic Cactus & Succulent Mix', sub: 'Potting Soil', desc: 'Fast-draining mineral soil with pumice, perlite & lava grit.', price: 280, unit: '2 kg', img: '/images/hero_fertilizer.jpg', badge: null, cert: 'Chemical Free', benefits: ['Zero root rot drainage', 'Coarse porous grit', 'Ideal for cacti & succulents'] }
    ]
  },

  // 7. ORGANIC FOOD (30)
  {
    catId: 'organic-food',
    catName: 'Organic Food',
    prefix: 'of',
    items: [
      { name: 'Organic Traditional Basmati Rice', sub: 'Grains & Millets', desc: 'Aromatic long-grain unpolished organic Basmati rice.', price: 249, unit: '1 kg', img: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['Rich natural aroma', 'Low glycemic index', 'Zero chemical pesticides'] },
      { name: 'Organic Brown Sonamasuri Rice', sub: 'Grains & Millets', desc: 'Whole grain fiber-rich organic brown Sonamasuri rice.', price: 165, unit: '1 kg', img: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['High bran fiber', 'Diabetes friendly rice', 'Heart healthy whole grain'] },
      { name: 'Organic Foxtail Millet (Kangni)', sub: 'Grains & Millets', desc: 'Ancient gluten-free foxtail millet rich in dietary fiber.', price: 140, unit: '1 kg', img: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['Gluten free super-food', 'High calcium & iron', 'Low GI millet'] },
      { name: 'Organic Raw White Quinoa', sub: 'Nuts & Seeds', desc: 'Complete protein whole grain white quinoa seeds.', price: 299, unit: '500g', img: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Contains 9 essential amino acids', 'High fiber content', 'Easy to digest grain'] },
      { name: 'Organic Turmeric Powder (Haldi)', sub: 'Spices & Herbs', desc: 'High 5%+ Curcumin organic Lakadong turmeric powder.', price: 180, unit: '250g', img: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['High Curcumin immunity', 'Natural anti-inflammatory', 'Zero lead chromate adulteration'] },
      { name: 'Cold Pressed Mustard Oil', sub: 'Oils & Ghee', desc: 'Traditional Kachi Ghani cold-pressed mustard oil in glass bottle.', price: 290, unit: '1 L', img: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['Rich in Omega-3 & 6', 'Authentic pungent aroma', 'Heart friendly MUFA'] },
      { name: 'A2 Desi Cow Ghee', sub: 'Oils & Ghee', desc: 'Traditional Bilona churned A2 ghee from grass-fed Gir cows.', price: 1450, unit: '500 ml', img: 'https://images.unsplash.com/photo-1589927986089-35812388d1f4?w=600&auto=format&fit=crop&q=80', badge: 'Top Rated', cert: '100% Organic', benefits: ['Bilona Vedic method', 'Rich in A2 beta-casein', 'Aromatic golden ghee'] },
      { name: 'Raw Wild Forest Honey', sub: 'Sweeteners', desc: 'Unfiltered, unheated raw wild honey collected from forest beehives.', price: 420, unit: '500g', img: 'https://images.unsplash.com/photo-1587049352847-4a222e784d38?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['Pure pollen & propolis', 'Natural cough remedy', 'Zero corn syrup blending'] },
      { name: 'Organic Chia Seeds', sub: 'Nuts & Seeds', desc: 'Raw organic black chia seeds high in Omega-3 & soluble fiber.', price: 220, unit: '250g', img: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Omega-3 superseed', 'High mucilage fiber', 'Weight management support'] },
      { name: 'Organic Brown Flax Seeds', sub: 'Nuts & Seeds', desc: 'Roasted or raw organic flaxseeds packed with lignans.', price: 130, unit: '250g', img: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['High ALA Omega-3', 'Hormonal balance lignans', 'Heart health seed'] },
      { name: 'Pink Himalayan Rock Salt', sub: 'Spices & Herbs', desc: '100% Pure unrefined coarse pink rock salt with 84 minerals.', price: 95, unit: '1 kg', img: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=80', badge: null, cert: 'Chemical Free', benefits: ['84 Trace minerals', 'Balances body pH', 'Unrefined natural salt'] },
      { name: 'Organic Jaggery Powder (Gud)', sub: 'Sweeteners', desc: 'Chemical-free unrefined cane jaggery powder rich in iron.', price: 110, unit: '1 kg', img: 'https://images.unsplash.com/photo-1587049352847-4a222e784d38?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['Natural healthy sweetener', 'Rich in iron & minerals', 'No sulfur bleaching'] },
      { name: 'Organic Whole Wheat Flour (Atta)', sub: 'Flours', desc: 'Stone-ground Chakki fresh organic MP Sharbati wheat flour.', price: 220, unit: '5 kg', img: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['Soft fluffy rotis', '100% Whole wheat bran', 'Zero maida blending'] },
      { name: 'Organic Toor Dal (Arhar)', sub: 'Pulses & Lentils', desc: 'Unpolished organic split yellow pigeon peas.', price: 195, unit: '1 kg', img: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['High plant protein', 'Unpolished natural dal', 'Easily digestible'] },
      { name: 'Organic Moong Dal Yellow', sub: 'Pulses & Lentils', desc: 'Split washed organic yellow moong dal for light khichdi.', price: 175, unit: '1 kg', img: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Lightest pulse on stomach', 'High protein content', 'Ideal for detox khichdi'] },
      { name: 'Organic Chana Dal', sub: 'Pulses & Lentils', desc: 'Unpolished organic Bengal gram split chickpeas.', price: 145, unit: '1 kg', img: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Low GI pulse', 'Rich in zinc & protein', 'Authentic nutty flavor'] },
      { name: 'Organic Rajma (Chitra Red)', sub: 'Pulses & Lentils', desc: 'Himalayan rainfed red kidney beans for rich Rajma curry.', price: 210, unit: '1 kg', img: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['High protein & iron', 'Himalayan rainfed crop', 'Soft melting texture'] },
      { name: 'Organic Kabuli Chana', sub: 'Pulses & Lentils', desc: 'Large bold organic white chickpeas for delicious Chole.', price: 185, unit: '1 kg', img: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Rich in dietary fiber', 'Bold creamy chickpeas', 'Zero synthetic polish'] },
      { name: 'Rolled Oats Whole Grain', sub: 'Grains & Millets', desc: '100% Whole grain rolled oats rich in beta-glucan fiber.', price: 195, unit: '1 kg', img: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Lowers cholesterol', 'Beta-glucan fiber', 'Heart healthy breakfast'] },
      { name: 'Organic Roasted Makhana', sub: 'Nuts & Seeds', desc: 'Lightly roasted organic fox nuts salted with rock salt.', price: 280, unit: '150g', img: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['Low calorie snack', 'Rich in calcium & potassium', 'Crunchy healthy munch'] },
      { name: 'Organic Cold Pressed Coconut Oil', sub: 'Oils & Ghee', desc: 'Edible virgin cold pressed coconut cooking oil.', price: 340, unit: '500 ml', img: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['MCT energy fats', 'High smoke point oil', '100% raw unrefined'] },
      { name: 'Organic Green Tea Leaves', sub: 'Spices & Herbs', desc: 'Whole leaf organic Darjeeling loose green tea.', price: 290, unit: '100g', img: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['EGCG metabolism booster', 'Fresh floral aroma', 'Pure whole tea leaf'] },
      { name: 'Organic Chamomile Tea', sub: 'Spices & Herbs', desc: 'Whole dried chamomile flowers for a calming bedtime tea.', price: 350, unit: '75g', img: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Promotes restful sleep', 'Soothes digestive tract', 'Caffeine free infusion'] },
      { name: 'Organic Ceylon Cinnamon Sticks', sub: 'Spices & Herbs', desc: 'True Ceylon sweet cinnamon quills low in coumarin.', price: 240, unit: '100g', img: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['True Ceylon cinnamon', 'Regulates blood sugar', 'Sweet fragrant spice'] },
      { name: 'Organic Green Cardamom Pods', sub: 'Spices & Herbs', desc: 'Bold 8mm green Elaichi pods with intense aromatic oil.', price: 450, unit: '100g', img: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', cert: '100% Organic', benefits: ['Natural mouth freshener', 'Rich essential volatile oil', 'Hand-sorted green pods'] },
      { name: 'Organic Cumin Seeds (Jeera)', sub: 'Spices & Herbs', desc: 'Aromatic rainfed organic Jeera seeds.', price: 160, unit: '250g', img: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Stimulates digestive enzymes', 'Rich earthy flavor', 'Clean & dust free'] },
      { name: 'Organic Whole Black Pepper', sub: 'Spices & Herbs', desc: 'Bold Malabar black peppercorns high in piperine.', price: 210, unit: '200g', img: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['High Piperine bioavailability', 'Enhances nutrient absorption', 'Pungent spicy flavor'] },
      { name: 'Organic Cloves (Laung)', sub: 'Spices & Herbs', desc: 'Hand-picked clove buds rich in eugenol essential oil.', price: 280, unit: '100g', img: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Eugenol dental care', 'Antimicrobial spice', 'High aromatic oil'] },
      { name: 'Organic Pumpkin Seeds', sub: 'Nuts & Seeds', desc: 'Raw AAA grade green pumpkin seeds packed with zinc.', price: 260, unit: '250g', img: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Zinc & magnesium powerhouse', 'Prostate & heart health', 'Crunchy salad topper'] },
      { name: 'Organic Sunflower Seeds', sub: 'Nuts & Seeds', desc: 'Raw unsalted sunflower seeds high in Vitamin E.', price: 160, unit: '250g', img: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80', badge: null, cert: '100% Organic', benefits: ['Vitamin E & selenium', 'Supports healthy skin', 'Crisp nutty snack'] }
    ]
  }
];

let allProducts = [];

categoriesData.forEach(cat => {
  cat.items.forEach((item, index) => {
    const id = `${cat.prefix}-${index + 1}`;
    allProducts.push({
      id,
      name: item.name,
      category: cat.catName,
      categoryId: cat.catId,
      subCategory: item.sub,
      shortDesc: item.name.length > 22 ? item.name : (item.name + ' - ' + item.sub),
      description: item.desc,
      price: item.price,
      originalPrice: Math.round(item.price * 1.25),
      unit: item.unit,
      rating: parseFloat((4.6 + (index % 5) * 0.08).toFixed(1)),
      reviewsCount: 45 + (index * 7),
      availability: 'In Stock',
      badge: item.badge,
      isBestseller: item.badge === 'Bestseller' || index % 4 === 0,
      isOrganic: true,
      image: item.img,
      certification: item.cert || '100% Organic',
      benefits: item.benefits
    });
  });
});

const content = `export const PRODUCTS = ${JSON.stringify(allProducts, null, 2)};\n`;
fs.writeFileSync(path.join(__dirname, '../src/data/products.js'), content, 'utf8');
console.log(`Successfully generated ${allProducts.length} products across 7 categories.`);
